service: docker

language: bash

notifications:
  email:
      - mitsuo_h@outlook.com

addons:
    apt:
        packages:
            - curl

before_install:
    - docker run --name latex -itd -v $PWD:/workdir johejo/debian-latex-jp:latest

script:
    - docker exec latex bash build.sh
- ./upload.sh